// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RequestTransferFormBackEnd.Data;

#nullable disable

namespace RequestTransferFormBackEnd.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251119062958_Priority")]
    partial class Priority
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RequestTransferFormBackEnd.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("RequestTransferFormBackEnd.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("RequestTransferFormBackEnd.Models.Amounttopay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<decimal>("amountTOPay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("amountToPayCreated")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("rentPaymentsAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("textForMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("userCreatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("UserId");

                    b.ToTable("Amounttopays");
                });

            modelBuilder.Entity("RequestTransferFormBackEnd.Models.Approval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApprovedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ApprovedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PreparedbyId")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("PreparedbyId");

                    b.ToTable("Approvals");
                });

            modelBuilder.Entity("RequestTransferFormBackEnd.Models.Bank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("bankAccount")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bankName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Banks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            bankAccount = "SA25 6000 0000 0271 2639 0001",
                            bankName = "Bank Al-Jazira 1"
                        },
                        new
                        {
                            Id = 2,
                            bankAccount = "SA95 6000 0000 0271 2639 0002",
                            bankName = "Bank Al-Jazira 2"
                        },
                        new
                        {
                            Id = 3,
                            bankAccount = "SA08 8000 0126 6080 1053 2348",
                            bankName = "Bank Al-Rajhi"
                        });
                });

            modelBuilder.Entity("RequestTransferFormBackEnd.Models.BankFacillities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AmountFacillitiesCreated")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("AmountOFFacillities")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BankId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("userCreatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BankId");

                    b.HasIndex("UserId");

                    b.ToTable("BankFacillities");
                });

            modelBuilder.Entity("RequestTransferFormBackEnd.Models.BankPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BankId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("BankPositionCreated")
                        .HasColumnType("datetime2");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BankId");

                    b.HasIndex("UserId");

                    b.ToTable("BankPositions");
                });

            modelBuilder.Entity("RequestTransferFormBackEnd.Models.Brands", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("brandName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            brandName = "Golden Star"
                        },
                        new
                        {
                            Id = 2,
                            brandName = "Premier"
                        },
                        new
                        {
                            Id = 3,
                            brandName = "Salary"
                        },
                        new
                        {
                            Id = 4,
                            brandName = "VAT"
                        },
                        new
                        {
                            Id = 5,
                            brandName = "RentPayments"
                        },
                        new
                        {
                            Id = 6,
                            brandName = "Others"
                        });
                });

            modelBuilder.Entity("RequestTransferFormBackEnd.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("companyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("companyValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            companyName = "Adma Shamran Trading Co.",
                            companyValue = "Trading"
                        },
                        new
                        {
                            Id = 2,
                            companyName = "Adma Shamran Catering Co.",
                            companyValue = "Catering"
                        });
                });

            modelBuilder.Entity("RequestTransferFormBackEnd.Models.CustomerAmount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AmountCustomerCreated")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("AmountOFCusotmers")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerListId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("userCreatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomerListId");

                    b.HasIndex("UserId");

                    b.ToTable("CustomerAmounts");
                });

            modelBuilder.Entity("RequestTransferFormBackEnd.Models.CustomerList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("customerBranch")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CustomerLists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            customerBranch = "Riyadh",
                            customerName = "Abdul"
                        });
                });

            modelBuilder.Entity("RequestTransferFormBackEnd.Models.PaymentAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaymentCompletionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UploadedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PaymentCompletionId");

                    b.HasIndex("UploadedByUserId");

                    b.ToTable("PaymentAttachments");
                });

            modelBuilder.Entity("RequestTransferFormBackEnd.Models.PaymentCompletion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AttachmentsDone")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AttachmentsDoneDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("OdooEntryDone")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("OdooEntryDoneDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("PaymentDone")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PaymentDoneDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PreparedbyId")
                        .HasColumnType("int");

                    b.Property<int>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("odooReferenceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PreparedbyId");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("PaymentCompletions");
                });

            modelBuilder.Entity("RequestTransferFormBackEnd.Models.Preparedby", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("VendorId")
                        .HasColumnType("int");

                    b.Property<decimal>("balanceAsPerAdmaShamran")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("balanceAsPerSupplier")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("difference")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("paymentDue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("preparedByCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("priorityName")
                        .HasColumnType("int");

                    b.Property<string>("reasonOFDifference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("userCreatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("VendorId");

                    b.ToTable("Preparedbies");
                });

            modelBuilder.Entity("RequestTransferFormBackEnd.Models.Priority", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("priorityName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("priorities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            priorityName = "First Priority"
                        },
                        new
                        {
                            Id = 2,
                            priorityName = "Second Priority"
                        });
                });

            modelBuilder.Entity("RequestTransferFormBackEnd.Models.Roles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("roleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            roleName = "FORM PREPARE"
                        },
                        new
                        {
                            Id = 2,
                            roleName = "VERIFIER"
                        },
                        new
                        {
                            Id = 3,
                            roleName = "APPROVER"
                        },
                        new
                        {
                            Id = 4,
                            roleName = "FINANCE"
                        },
                        new
                        {
                            Id = 5,
                            roleName = "ADMIN"
                        });
                });

            modelBuilder.Entity("RequestTransferFormBackEnd.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("branch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("companyId")
                        .HasColumnType("int");

                    b.Property<string>("department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("iqamaNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("usercreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("workEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("companyId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RequestTransferFormBackEnd.Models.Vendorlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("bankAccount")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bankName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("branchName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("supplierName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Vendorlists");
                });

            modelBuilder.Entity("RequestTransferFormBackEnd.Models.Verified", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PreparedbyId")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VerifiedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("VerifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PreparedbyId");

                    b.HasIndex("VerifiedByUserId");

                    b.ToTable("Verifieds");
                });

            modelBuilder.Entity("RequestTransferFormBackEnd.Models.preparedbyAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PreparedbyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UploadedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PreparedbyId");

                    b.HasIndex("UploadedByUserId");

                    b.ToTable("PreparedbyAttachments");
                });

            modelBuilder.Entity("RequestTransferFormBackEnd.Models.Amounttopay", b =>
                {
                    b.HasOne("RequestTransferFormBackEnd.Models.Brands", "Brand")
                        .WithMany("Amounttopays")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RequestTransferFormBackEnd.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RequestTransferFormBackEnd.Models.Approval", b =>
                {
                    b.HasOne("RequestTransferFormBackEnd.Models.User", "ApprovedByUser")
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RequestTransferFormBackEnd.Models.Preparedby", "Preparedby")
                        .WithMany("Approvals")
                        .HasForeignKey("PreparedbyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ApprovedByUser");

                    b.Navigation("Preparedby");
                });

            modelBuilder.Entity("RequestTransferFormBackEnd.Models.BankFacillities", b =>
                {
                    b.HasOne("RequestTransferFormBackEnd.Models.Bank", "Bank")
                        .WithMany("BankFacillity")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RequestTransferFormBackEnd.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Bank");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RequestTransferFormBackEnd.Models.BankPosition", b =>
                {
                    b.HasOne("RequestTransferFormBackEnd.Models.Bank", "Bank")
                        .WithMany("BankPositions")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RequestTransferFormBackEnd.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bank");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RequestTransferFormBackEnd.Models.CustomerAmount", b =>
                {
                    b.HasOne("RequestTransferFormBackEnd.Models.CustomerList", "CustomerList")
                        .WithMany("CustomerAmounts")
                        .HasForeignKey("CustomerListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RequestTransferFormBackEnd.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerList");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RequestTransferFormBackEnd.Models.PaymentAttachment", b =>
                {
                    b.HasOne("RequestTransferFormBackEnd.Models.PaymentCompletion", "PaymentCompletion")
                        .WithMany("Attachments")
                        .HasForeignKey("PaymentCompletionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RequestTransferFormBackEnd.Models.User", "UploadedByUser")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("PaymentCompletion");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("RequestTransferFormBackEnd.Models.PaymentCompletion", b =>
                {
                    b.HasOne("RequestTransferFormBackEnd.Models.Preparedby", "Preparedby")
                        .WithMany("PaymentCompletions")
                        .HasForeignKey("PreparedbyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RequestTransferFormBackEnd.Models.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Preparedby");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("RequestTransferFormBackEnd.Models.Preparedby", b =>
                {
                    b.HasOne("RequestTransferFormBackEnd.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RequestTransferFormBackEnd.Models.Vendorlist", "Vendor")
                        .WithMany("PreparedBies")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("RequestTransferFormBackEnd.Models.User", b =>
                {
                    b.HasOne("RequestTransferFormBackEnd.Models.Roles", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RequestTransferFormBackEnd.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("companyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("RequestTransferFormBackEnd.Models.Verified", b =>
                {
                    b.HasOne("RequestTransferFormBackEnd.Models.Preparedby", "Preparedby")
                        .WithMany("Verifications")
                        .HasForeignKey("PreparedbyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RequestTransferFormBackEnd.Models.User", "VerifiedByUser")
                        .WithMany()
                        .HasForeignKey("VerifiedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Preparedby");

                    b.Navigation("VerifiedByUser");
                });

            modelBuilder.Entity("RequestTransferFormBackEnd.Models.preparedbyAttachment", b =>
                {
                    b.HasOne("RequestTransferFormBackEnd.Models.Preparedby", "Preparedby")
                        .WithMany("Attachments")
                        .HasForeignKey("PreparedbyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RequestTransferFormBackEnd.Models.User", "UploadedByUser")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Preparedby");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("RequestTransferFormBackEnd.Models.Bank", b =>
                {
                    b.Navigation("BankFacillity");

                    b.Navigation("BankPositions");
                });

            modelBuilder.Entity("RequestTransferFormBackEnd.Models.Brands", b =>
                {
                    b.Navigation("Amounttopays");
                });

            modelBuilder.Entity("RequestTransferFormBackEnd.Models.CustomerList", b =>
                {
                    b.Navigation("CustomerAmounts");
                });

            modelBuilder.Entity("RequestTransferFormBackEnd.Models.PaymentCompletion", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("RequestTransferFormBackEnd.Models.Preparedby", b =>
                {
                    b.Navigation("Approvals");

                    b.Navigation("Attachments");

                    b.Navigation("PaymentCompletions");

                    b.Navigation("Verifications");
                });

            modelBuilder.Entity("RequestTransferFormBackEnd.Models.Roles", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("RequestTransferFormBackEnd.Models.Vendorlist", b =>
                {
                    b.Navigation("PreparedBies");
                });
#pragma warning restore 612, 618
        }
    }
}
